### ISSUE TITLE
Error: could not find tiller

### ISSUE THREAD

**Issue by NhatAnh** [yinondn/seldon-core-quickstart-tutorial#1]
Hi,
When I run `helm install ambassador --namespace ambassador datawire/ambassador` I got error `Error: could not find tiller`

Although I have searched google about this error, I still couldn't fix this. Can you help?

BTW, what version is your Kubernetes?

**Comment by yinondn** [comment]
Hi,
1. The Kubernetes version used in this tutorial is 1.21
2. About this error I don't know, look at this and ask in Helm forums:
https://stackoverflow.com/questions/51646957/helm-could-not-find-tiller

**Comment by NhatAnh** [comment]
Thank you. I ran `brew upgrade helm` and it works now.
